image: archlinux
packages:
  - rust
sources:
  - https://git.sr.ht/~kennylevinsen/greetd
tasks:
  - rustfmt-check: |
      cd greetd
      cargo fmt -- --check
  - build: |
      cd greetd
      cargo build
