[package]
name = "agreety"
version = "0.5.0"
authors = ["Kenny Levinsen <kl@kl.wtf>"]
edition = "2018"

[dependencies]
greet_proto = { path = "../greet_proto", features = ["sync-codec"]}
rust-ini = "0.14"
rpassword = "4.0"
getopts = "0.2"
nix = "0.16"