[package]
name = "greetd"
version = "0.1.1"
authors = ["Kenny Levinsen <kl@kl.wtf>"]
edition = "2018"

[dependencies]
nix = "0.16"
pam-sys = "0.5.6"
users = "0.9.1"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
greet_proto = { path = "../greet_proto" }
libc = "0.2"
futures = "0.3"
tokio = { version = "0.2", features = ["net", "sync", "macros", "signal", "rt-util", "io-util", "time"] }
getopts = "0.2"
thiserror = "1.0"
async-trait = "0.1"