[package]
name = "greetd"
version = "0.1.1"
authors = ["Kenny Levinsen <kl@kl.wtf>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.15"
pam-sys = "0.5.6"
users = "0.9.1"
clap = "2.33"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
greet_proto = { path = "../greet_proto" }
libc = "0.2"
byteorder = "1.3"
