[package]
name = "greet_proto"
version = "0.2.0"
authors = ["Kenny Levinsen <kl@kl.wtf>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
